name: Report Commits to Splunk

on:
  push:
    branches:
      - main

jobs:
  report-to-splunk:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Splunk
        run: |
          curl -k https://54.84.251.105:8088/services/collector/event \
            -H "Authorization: Splunk ${{ secrets.SPLUNK_HEC_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "event": {
                "repository": "${{ github.repository }}",
                "pusher": "${{ github.actor }}",
                "commit": "${{ github.sha }}",
                "message": "${{ github.event.head_commit.message }}"
              },
              "sourcetype": "_json"
            }'


            
                        