name: Send Metrics to Splunk

on:
  push:
    branches:
      - main

jobs:
  send-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment metric to Splunk
        run: |
          curl -X POST ${{ secrets.SPLUNK_OBSERVABILITY_URL }} \
            -H "Authorization: Bearer ${{ secrets.SPLUNK_OBSERVABILITY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "eventType": "ci_cd_event",
              "category": "DEPLOYMENT",
              "timestamp": '"$(date +%s)"',
              "dimensions": {
                "workflow": "${{ github.workflow }}",
                "job": "${{ github.job }}",
                "status": "success",
                "repository": "${{ github.repository }}"
              }
            }'
